### ISSUE TITLE
Fix deprecation warning about the use of conn/0

### ISSUE THREAD

**Issue by dmitrinesterenko** [dmitrinesterenko/blog#53]
warning: using conn/0 to build a connection is deprecated. Use build_conn/0 instead.
    test/controllers/writer_controller_test.exs:7: BlogPhoenix.WriterControllerTest."test GET /write"/1
    (ex_unit) lib/ex_unit/runner.ex:296: ExUnit.Runner.exec_test/1
    (stdlib) timer.erl:166: :timer.tc/1
    (ex_unit) lib/ex_unit/runner.ex:246: anonymous fn/3 in ExUnit.Runner.spawn_test/3

**Comment by dmitrinesterenko** [comment]
Resolved in #77
